/**
 * ENUM file.
 */
;

const WEBSOCKET_MESSAGE_TYPES = {
  // LOBBY TOPIC
  LOBBY_LIST_CHANGED: 'LOBBY_LIST_CHANGED',
  LOBBY_PLAYER_CHANGED: 'LOBBY_PLAYER_CHANGED',
  PLAYER_LEFT_LOBBY: 'PLAYER_LEFT_LOBBY',
  GAME_STARTED: 'GAME_STARTED',
  // GAME TOPIC
  PLAYER_ENDED_TURN: 'PLAYER_ENDED_TURN',
  PLAYER_LEFT_GAME: 'PLAYER_LEFT_GAME',
  // GAME BOARD VIEW TOPIC
  ARMY_MOVED_UNCONTESTED: 'ARMY_MOVED_UNCONTESTED',
  ARMY_STANCE_CHANGED: 'ARMY_STANCE_CHANGED',
  ARMY_UNITS_UPDATED: 'ARMY_UNITS_UPDATED',
  SETTLER_MOVED_UNCONTESTED: 'SETTLER_MOVED_UNCONTESTED',
  SETTLER_CREATED_CITY: 'SETTLER_CREATED_CITY',
  SUPERCHARGE_PERFORMED: 'SUPERCHARGE_PERFORMED',
  // CITY TOPIC
  CITY_STATE_UPDATED: 'CITY_STATE_UPDATED',
  UNIT_RECRUITMENT_QUEUE_UPDATED: 'UNIT_RECRUITMENT_QUEUE_UPDATED',
  UNASSIGNED_UNITS_UPDATED: 'UNASSIGNED_UNITS_UPDATED',
  ARMY_AND_UNASSIGNED_UNITS_UPDATED: 'ARMY_AND_UNASSIGNED_UNITS_UPDATED',
  ARMY_SPAWNED_FROM_CITY: 'ARMY_SPAWNED_FROM_CITY',
  TIME_WARP_PERFORMED: 'TIME_WARP_PERFORMED',
  PREPARE_OUTSIDE_CITY_WALLS_PROMPT: 'PREPARE_OUTSIDE_CITY_WALLS_PROMPT',
  CITY_SCORCHED: 'CITY_SCORCHED',
  CONFIRM_ATTACK_CITY_WALLS_PROMPT: 'CONFIRM_ATTACK_CITY_WALLS_PROMPT',
  // BATTLE TOPIC
  BATTLE_INITIATED: 'BATTLE_INITIATED',
  BATTLE_STARTED: 'BATTLE_STARTED',
  BATTLE_DATA_UPDATED: 'BATTLE_DATA_UPDATED',
  BATTLE_ENDED: 'BATTLE_ENDED',
  ORBITAL_FRACTURE_PERFORMED: 'ORBITAL_FRACTURE_PERFORMED',
  // CHAT TOPIC
  NEW_GLOBAL_CHAT_MESSAGE: 'NEW_GLOBAL_CHAT_MESSAGE',
  NEW_LOBBY_CHAT_MESSAGE: 'NEW_LOBBY_CHAT_MESSAGE',
  NEW_GAME_CHAT_MESSAGE: 'NEW_GAME_CHAT_MESSAGE',
};

export default WEBSOCKET_MESSAGE_TYPES;
