/* eslint-disable max-len */
const reducerActionTypes = {
  SET_BATTLE_DATA: 'SET_BATTLE_DATA',
  SET_SHOW_ENEMY_ARMY_IN_BATTLE: 'SET_SHOW_ENEMY_ARMY_IN_BATTLE',
  SET_OWN_ARMY_SUBMITTED: 'SET_OWN_ARMY_SUBMITTED',
  SET_SELECTED_BATTLE_UNIT_INDEX: 'SET_SELECTED_BATTLE_UNIT_INDEX',
  SET_ACTIVE_ABILITY_TARGET_SELECTION: 'SET_ACTIVE_ABILITY_TARGET_SELECTION',
  CLEAR_BATTLE_VIEW_REDUCER: 'CLEAR_BATTLE_VIEW_REDUCER',
  SET_SELECTED_MULTIPLE_ENEMY_UNIT_INDICES: 'SET_SELECTED_MULTIPLE_ENEMY_UNIT_INDICES',
  SET_MULTIPLE_ENEMY_SELECTION_COUNT_REMAINING: 'SET_MULTIPLE_ENEMY_SELECTION_COUNT_REMAINING',
  CLEAR_UNIT_ACTION_SELECTION: 'CLEAR_UNIT_ACTION_SELECTION',
  SET_ACTION_MESSAGE: 'SET_ACTION_MESSAGE',
};

export default reducerActionTypes;
