const reducerActionTypes = {
  SET_BATTLE_DATA: 'SET_BATTLE_DATA',
  SET_SHOW_ENEMY_ARMY_IN_BATTLE: 'SET_SHOW_ENEMY_ARMY_IN_BATTLE',
  SET_OWN_ARMY_SUBMITTED: 'SET_OWN_ARMY_SUBMITTED',
  SET_SELECTED_BATTLE_UNIT_INDEX: 'SET_SELECTED_BATTLE_UNIT_INDEX',
};

export default reducerActionTypes;
