/* eslint-disable max-len */
const reducerActionTypes = {
  SET_SELECTED_CHAT_TOPIC: 'SET_SELECTED_CHAT_TOPIC',
  SET_GLOBAL_MESSAGES: 'SET_GLOBAL_MESSAGES',
  SET_LOBBY_MESSAGES: 'SET_LOBBY_MESSAGES',
  SET_GAME_MESSAGES: 'SET_GAME_MESSAGES',
  CLEAR_CHAT_REDUCER_EXCEPT_GLOBAL_MESSAGES: 'CLEAR_CHAT_REDUCER_EXCEPT_GLOBAL_MESSAGES',
};

export default reducerActionTypes;
