const reducerActionTypes = {
  SET_CITY_MENU_TAB: 'SET_CITY_MENU_TAB',
  SET_CITY_MENU_SUPPLEMENTAL_VIEW: 'SET_CITY_MENU_SUPPLEMENTAL_VIEW',
  SET_CITY_MENU_SUPPLEMENTAL_DATA: 'SET_CITY_MENU_SUPPLEMENTAL_DATA',
  CLEAR_CITY_MENU_REDUCER: 'CLEAR_CITY_MENU_REDUCER',
};

export default reducerActionTypes;
