const reducerActionTypes = {
  SET_SHOW_CITY_MODAL_INFO: 'SET_SHOW_CITY_MODAL_INFO',
  SET_SHOW_RESEARCH_MODAL_INFO: 'SET_SHOW_RESEARCH_MODAL_INFO',
  SET_CITY_MENU_TAB: 'SET_CITY_MENU_TAB',
  SET_CITY_MENU_SUPPLEMENTAL_VIEW: 'SET_CITY_MENU_SUPPLEMENTAL_VIEW',
  SET_CITY_MENU_SUPPLEMENTAL_DATA: 'SET_CITY_MENU_SUPPLEMENTAL_DATA',
};

export default reducerActionTypes;
