const reducerActionTypes = {
  SET_GAME_VIEW: 'SET_GAME_VIEW',
  SET_GAME_ID: 'SET_GAME_ID',
  SET_PLAYER_ONE: 'SET_PLAYER_ONE',
  SET_PLAYER_TWO: 'SET_PLAYER_TWO',
  SET_GAME_BOARD: 'SET_GAME_BOARD',
  SET_MAIN_PANEL_VIEW: 'SET_MAIN_PANEL_VIEW',
  SET_SUPPLEMENTAL_PANEL_VIEW: 'SET_SUPPLEMENTAL_PANEL_VIEW',
  SET_MAIN_PANEL_DATA: 'SET_MAIN_PANEL_DATA',
  SET_SUPPLEMENTAL_PANEL_DATA: 'SET_SUPPLEMENTAL_PANEL_DATA',
};

export default reducerActionTypes;
