const reducerActionTypes = {
  SET_PLAYER_ONE: 'SET_PLAYER_ONE',
  SET_PLAYER_TWO: 'SET_PLAYER_TWO',
  SET_OWN_PLAYER_NUMBER: 'SET_OWN_PLAYER_NUMBER',
  SET_PLAYER_WHOSE_TURN_IT_IS: 'SET_PLAYER_WHOSE_TURN_IT_IS',
  SET_WINNING_PLAYER: 'SET_WINNING_PLAYER',
  CLEAR_GAME_PLAYER_REDUCER: 'CLEAR_GAME_PLAYER_REDUCER',
};

export default reducerActionTypes;
