const reducerActionTypes = {
  SET_GAME_BOARD: 'SET_GAME_BOARD',
  SET_MAIN_PANEL_VIEW: 'SET_MAIN_PANEL_VIEW',
  SET_SUPPLEMENTAL_PANEL_VIEW: 'SET_SUPPLEMENTAL_PANEL_VIEW',
  SET_IS_MOVING_ARMY: 'SET_IS_MOVING_ARMY',
  SET_VIEWING_ARMY_IN_CITY: 'SET_VIEWING_ARMY_IN_CITY',
  SET_SELECTED_TILE_POSITION: 'SET_SELECTED_TILE_POSITION',
};

export default reducerActionTypes;
