const reducerActionTypes = {
  SET_GAME_VIEW: 'SET_GAME_VIEW',
  SET_GAME_ID: 'SET_GAME_ID',
  SET_PLAYER_ONE_USERNAME: 'SET_PLAYER_ONE_USERNAME',
  SET_PLAYER_TWO_USERNAME: 'SET_PLAYER_TWO_USERNAME',
};

export default reducerActionTypes;
