const reducerActionTypes = {
  SET_GAME_BOARD: 'SET_GAME_BOARD',
  SET_MAIN_PANEL_VIEW: 'SET_MAIN_PANEL_VIEW',
  SET_SUPPLEMENTAL_PANEL_VIEW: 'SET_SUPPLEMENTAL_PANEL_VIEW',
  SET_IS_MOVING_ARMY: 'SET_IS_MOVING_ARMY',
  SET_IS_MOVING_SETTLER: 'SET_IS_MOVING_SETTLER',
  SET_SELECTED_TILE_POSITION: 'SET_SELECTED_TILE_POSITION',
  SET_UNCLOSEABLE_MODAL_VIEW: 'SET_UNCLOSEABLE_MODAL_VIEW',
};

export default reducerActionTypes;
