const reducerActionTypes = {
  SET_GAME_VIEW: 'SET_GAME_VIEW',
  SET_GAME_ID: 'SET_GAME_ID',
  SET_PLAYER_ONE: 'SET_PLAYER_ONE',
  SET_PLAYER_TWO: 'SET_PLAYER_TWO',
  SET_GAME_BOARD: 'SET_GAME_BOARD',
  SET_MAIN_PANEL_VIEW: 'SET_MAIN_PANEL_VIEW',
  SET_SUPPLEMENTAL_PANEL_VIEW: 'SET_SUPPLEMENTAL_PANEL_VIEW',
  SET_MAIN_PANEL_DATA: 'SET_MAIN_PANEL_DATA',
  SET_SUPPLEMENTAL_PANEL_DATA: 'SET_SUPPLEMENTAL_PANEL_DATA',
  SET_ACTION_BAR_VIEW: 'SET_ACTION_BAR_VIEW',
  SET_ACTION_BAR_DATA: 'SET_ACTION_BAR_DATA',
  SET_IS_MOVING_ARMY: 'SET_IS_MOVING_ARMY',
  SET_ACTION_BAR_TOOLTIP: 'SET_ACTION_BAR_TOOLTIP',
  SET_SELECTED_TILE_POSITION: 'SET_SELECTED_TILE_POSITION',
  SET_IS_OWN_TURN: 'SET_IS_OWN_TURN',
  SET_AWAITING_SERVER_CONFIRMATION: 'SET_AWAITING_SERVER_CONFIRMATION',
  SET_QUEUED_ACTION_COST: 'SET_QUEUED_ACTION_COST',
};

export default reducerActionTypes;
