/* eslint-disable max-len */
const reducerActionTypes = {
  SET_OWN_USERNAME: 'SET_OWN_USERNAME',
  SET_MAIN_VIEW: 'SET_MAIN_VIEW',
  SET_OWN_USER_ID: 'SET_OWN_USER_ID',
  SET_WEBSOCKET_TOPICS: 'SET_WEBSOCKET_TOPICS',
  CLEAR_GENERAL_REDUCER_EXCEPT_USER_DATA: 'CLEAR_GENERAL_REDUCER_EXCEPT_USER_DATA',
  SET_SAVED_GAMES: 'SET_SAVED_GAMES',
  SET_GAME_ID_BEING_RESTORED: 'SET_GAME_ID_BEING_RESTORED',
};

export default reducerActionTypes;
