const reducerActionTypes = {
  SET_ATTACKING_ARMY: 'SET_ATTACKING_ARMY',
  SET_CITY_UNDER_ATTACK: 'SET_CITY_UNDER_ATTACK',
  SET_SALLY_OUT_FORCES: 'SET_SALLY_OUT_FORCES',
  SET_OCCUPYING_ARMY: 'SET_OCCUPYING_ARMY',
  SET_INCLUDE_OCCUPYING_COMMANDER: 'SET_INCLUDE_OCCUPYING_COMMANDER',
  SET_EXCESS_DEFENDERS: 'SET_EXCESS_DEFENDERS',
};

export default reducerActionTypes;
