/* eslint-disable max-len */
const reducerActionTypes = {
  SET_ATTACKING_ARMY: 'SET_ATTACKING_ARMY',
  SET_CITY_UNDER_ATTACK: 'SET_CITY_UNDER_ATTACK',
  SET_SALLY_OUT_FORCES: 'SET_SALLY_OUT_FORCES',
  SET_OCCUPYING_ARMY: 'SET_OCCUPYING_ARMY',
  SET_INCLUDE_OCCUPYING_COMMANDER: 'SET_INCLUDE_OCCUPYING_COMMANDER',
  SET_EXCESS_DEFENDERS: 'SET_EXCESS_DEFENDERS',
  SET_CITY_TILE_POSITION: 'SET_CITY_TILE_POSITION',
  SET_ATTACKING_ARMY_TILE_POSITION: 'SET_ATTACKING_ARMY_TILE_POSITION',
  CLEAR_OUTSIDE_CITY_WALLS_BATTLE_REDUCER: 'CLEAR_OUTSIDE_CITY_WALLS_BATTLE_REDUCER',
};

export default reducerActionTypes;
