/**
 * Enum
 */
const ARMY_ACTIONS_VIEW = 'ARMY_ACTIONS_VIEW';
const CITY_ACTIONS_VIEW = 'CITY_ACTIONS_VIEW';
const NONE = 'NONE';

const ACTION_BAR_VIEWS = {
  ARMY_ACTIONS_VIEW: ARMY_ACTIONS_VIEW,
  CITY_ACTIONS_VIEW: CITY_ACTIONS_VIEW,
  NONE: NONE,
};

export default ACTION_BAR_VIEWS;
