/* eslint-disable max-len */
/**
 * ENUM file.
 */

const ADVANCED_DETAILS_MODAL_VIEW = {
  NONE: 'NONE',
  CITY_MENU: 'CITY_MENU',
  ATTACK_CITY_WALLS_CONFIRMATION_DIALOG: 'ATTACK_CITY_WALLS_CONFIRMATION_DIALOG',
};

export default ADVANCED_DETAILS_MODAL_VIEW;
