/**
 * ENUM file.
 */
import ARMY_ACTIONS from './armyActions';

const HUMANS_NAME = 'HUMANS';
const HUMANS_ACTION_BAR_DATA = [ARMY_ACTIONS.CAMP];
const INSECTS_NAME = 'INSECTS';
const INSECTS_ACTION_BAR_DATA = [ARMY_ACTIONS.CAMP];

const FACTIONS = {
  HUMANS: {
    NAME: HUMANS_NAME,
    ACTION_BAR_DATA: HUMANS_ACTION_BAR_DATA,
  },
  INSECTS: {
    NAME: INSECTS_NAME,
    ACTION_BAR_DATA: INSECTS_ACTION_BAR_DATA,
  },
};

export default FACTIONS;
