/**
 * ENUM file.
 */
;

const WEBSOCKET_MESSAGE_TYPES = {
  ARMY_MOVED_UNCONTESTED: 'ARMY_MOVED_UNCONTESTED',
  ARMY_STANCE_CHANGED: 'ARMY_STANCE_CHANGED',
  PLAYER_ENDED_TURN: 'PLAYER_ENDED_TURN',
};

export default WEBSOCKET_MESSAGE_TYPES;
